create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null,
  text text not null,
  rating numeric not null check (rating >= 0.5 and rating <= 5),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
to anon
using (true);

drop policy if exists "Anyone can insert comments" on public.comments;
create policy "Anyone can insert comments"
on public.comments for insert
to anon
with check (
  char_length(name) between 1 and 40
  and char_length(text) between 1 and 220
  and rating >= 0.5
  and rating <= 5
);

drop policy if exists "Anyone can delete comments" on public.comments;
create policy "Anyone can delete comments"
on public.comments for delete
to anon
using (true);
